"""
worker/tasks.py
Core review logic:
  1. Fetch the PR unified diff from GitHub
  2. Send it to OpenAI for analysis
  3. Post the structured review as a PR comment on GitHub
"""
import json
import os
from typing import Any, Dict

import httpx
from openai import AsyncOpenAI

from api.config import get_settings

# ── OpenAI system prompt ──────────────────────────────────────────────────────

SYSTEM_PROMPT = """You are a senior software engineer performing a thorough pull request review.
You will receive a unified diff from a GitHub Pull Request.

Return ONLY a valid JSON object — no markdown fences, no extra text — matching this exact schema:
{
  "summary": "<2-3 sentence overall assessment>",
  "score": <integer 1-10>,
  "verdict": "approve" | "request_changes" | "comment",
  "issues": [
    {
      "severity": "critical" | "warning" | "suggestion",
      "file": "<filename or 'general'>",
      "line": "<line number, range, or null>",
      "message": "<clear description of the issue and how to fix it>"
    }
  ],
  "positives": ["<something the author did well>"],
  "review_body": "<full GitHub markdown comment — see format below>"
}

Format the review_body as a polished GitHub markdown comment:
## 🤖 AI Code Review  (Score: X/10)

### Summary
<overall assessment>

### ✅ Positives
- <positive 1>

### ⚠️ Issues
| Severity | File | Line | Issue |
|---|---|---|---|
| 🔴 Critical / 🟡 Warning / 🔵 Suggestion | file | line | message |

### 💡 Recommendations
<key action items>

---
*Review generated by AI Code Reviewer*

Be specific, constructive, and actionable. Reference file names and line numbers where possible.
"""


# ── GitHub helpers ─────────────────────────────────────────────────────────────

async def _fetch_diff(diff_url: str, token: str) -> str:
    """Download the unified diff for the PR."""
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3.diff",
    }
    async with httpx.AsyncClient(timeout=30) as client:
        resp = await client.get(diff_url, headers=headers, follow_redirects=True)
        resp.raise_for_status()
        return resp.text


async def _post_pr_comment(repo_full_name: str, pr_number: int, body: str, token: str) -> Dict:
    """Post a comment to the GitHub PR."""
    url = f"https://api.github.com/repos/{repo_full_name}/issues/{pr_number}/comments"
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    async with httpx.AsyncClient(timeout=20) as client:
        resp = await client.post(url, headers=headers, json={"body": body})
        resp.raise_for_status()
        return resp.json()


async def _post_review(
    repo_full_name: str,
    pr_number: int,
    head_sha: str,
    body: str,
    verdict: str,
    token: str,
) -> Dict:
    """
    Submit a formal GitHub PR Review (approve / request_changes / comment).
    Falls back to a plain comment if head_sha is missing.
    """
    if not head_sha:
        return await _post_pr_comment(repo_full_name, pr_number, body, token)

    event_map = {
        "approve": "APPROVE",
        "request_changes": "REQUEST_CHANGES",
        "comment": "COMMENT",
    }
    github_event = event_map.get(verdict, "COMMENT")

    url = f"https://api.github.com/repos/{repo_full_name}/pulls/{pr_number}/reviews"
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    payload = {"commit_id": head_sha, "body": body, "event": github_event}

    async with httpx.AsyncClient(timeout=20) as client:
        resp = await client.post(url, headers=headers, json=payload)
        resp.raise_for_status()
        return resp.json()


# ── Main review job ────────────────────────────────────────────────────────────

async def run_review_job(
    repo_full_name: str,
    pr_number: int,
    diff_url: str,
    head_sha: str = "",
) -> Dict[str, Any]:
    """
    Orchestrates the full review pipeline:
      fetch diff → call OpenAI → post GitHub review → return summary dict
    """
    settings = get_settings()
    print(f"[worker] Starting review: {repo_full_name} PR #{pr_number}")

    # ── 1. Fetch diff ──────────────────────────────────────────────────────
    if not diff_url:
        diff_url = f"https://github.com/{repo_full_name}/pull/{pr_number}.diff"

    try:
        diff = await _fetch_diff(diff_url, settings.github_token)
    except Exception as exc:
        print(f"[worker] ERROR fetching diff: {exc}")
        return {"error": f"Could not fetch PR diff: {exc}"}

    # Truncate very large diffs to stay within token limits
    if len(diff) > settings.max_diff_chars:
        diff = diff[: settings.max_diff_chars] + "\n\n[... diff truncated ...]"

    if not diff.strip():
        return {"summary": "Empty diff — nothing to review.", "score": None}

    # ── 2. Call OpenAI ─────────────────────────────────────────────────────
    client = AsyncOpenAI(api_key=settings.openai_api_key)

    try:
        response = await client.chat.completions.create(
            model=settings.openai_model,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {
                    "role": "user",
                    "content": (
                        f"Repository: {repo_full_name}\n"
                        f"PR #{pr_number}\n\n"
                        f"Diff:\n```diff\n{diff}\n```"
                    ),
                },
            ],
            temperature=0.2,
            max_tokens=2000,
            response_format={"type": "json_object"},
        )
    except Exception as exc:
        print(f"[worker] ERROR calling OpenAI: {exc}")
        return {"error": f"OpenAI call failed: {exc}"}

    raw = response.choices[0].message.content
    try:
        review_data = json.loads(raw)
    except json.JSONDecodeError:
        print(f"[worker] ERROR parsing OpenAI JSON: {raw[:200]}")
        return {"error": "Failed to parse AI response as JSON.", "raw": raw}

    review_body = review_data.get("review_body", review_data.get("summary", "Review complete."))
    verdict     = review_data.get("verdict", "comment")
    score       = review_data.get("score")

    print(f"[worker] Review done — score: {score}/10, verdict: {verdict}")

    # ── 3. Post to GitHub ──────────────────────────────────────────────────
    if settings.github_token:
        try:
            await _post_review(
                repo_full_name=repo_full_name,
                pr_number=pr_number,
                head_sha=head_sha,
                body=review_body,
                verdict=verdict,
                token=settings.github_token,
            )
            print(f"[worker] Review posted to GitHub PR #{pr_number}")
        except Exception as exc:
            print(f"[worker] WARNING: Could not post review to GitHub: {exc}")
            review_data["github_post_error"] = str(exc)
    else:
        print("[worker] GITHUB_TOKEN not set — skipping GitHub post.")

    return {
        "summary": review_data.get("summary"),
        "score": score,
        "verdict": verdict,
        "issues": review_data.get("issues", []),
        "positives": review_data.get("positives", []),
    }
